version: '{build}'
os: Windows Server 2012
build_script:
  - mvn clean package --batch-mode -DskipTest
  - mvn --version
test_script:
  - mvn clean install --batch-mode
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
